#!/bin/bash

# For Debian Linux
# Tested on Linux 4.19.0-kali3-amd64 #1 SMP Debian 4.19.20-1kali1 (2019-02-14) x86_64 GNU/Linux

echo "Installing..."

echo "Sierra Theme"
cp -r "Sierra Theme" "/usr/share/themes/Sierra Theme"

echo "Mojave - Sierra Cursor"
cp -r "Sierra Cursor" "/usr/share/icons/Sierra Cursor"

echo "Mojave - Sierra Icons"
cp -r "Sierra Icons" "/usr/share/icons/Sierra Icons"

echo "Completed"